export const data = [
  { name: "PHILIPPI", "service requests": 24647 },
  { name: "GUGULETU", "service requests": 14108 },
  { name: "STRAND", "service requests": 9866 },
  { name: "BONTEHEUWEL", "service requests": 8742 },
  { name: "HOUT BAY", "service requests": 8482 },
  { name: "TAFELSIG", "service requests": 8384 },
  { name: "LANGA", "service requests": 8178 },
  { name: "LOTUS RIVER", "service requests": 8094 },
  { name: "MANENBERG", "service requests": 7673 },
  { name: "CLAREMONT", "service requests": 7501 },
  { name: "MFULENI", "service requests": 6766 },
  { name: "LANSDOWNE", "service requests": 6437 },
  { name: "STRANDFONTEIN", "service requests": 6149 },
  { name: "HANOVER PARK", "service requests": 5967 },
  { name: "PLUMSTEAD", "service requests": 5774 },
  { name: "PARKLANDS", "service requests": 5764 },
  { name: "CONSTANTIA", "service requests": 5706 },
  { name: "LENTEGEUR", "service requests": 5574 },
  { name: "NYANGA", "service requests": 5553 },
  { name: "RETREAT", "service requests": 5434 },
  { name: "GRASSY PARK", "service requests": 5370 },
  { name: "WOODSTOCK", "service requests": 5304 },
  { name: "SAXONSEA", "service requests": 5116 },
  { name: "WYNBERG", "service requests": 4941 },
  { name: "RONDEBOSCH", "service requests": 4744 },
  { name: "FISH HOEK", "service requests": 4718 },
  { name: "EERSTERIVIER", "service requests": 4650 },
  { name: "TABLE VIEW", "service requests": 4623 },
  { name: "PINELANDS", "service requests": 4595 },
  { name: "RAVENSMEAD", "service requests": 4511 },
  { name: "OTTERY", "service requests": 4485 },
  { name: "BISHOP LAVIS", "service requests": 4483 },
  { name: "BELLVILLE SOUTH", "service requests": 4263 },
  { name: "EASTRIDGE", "service requests": 4071 },
  { name: "STEENBERG", "service requests": 4027 },
  { name: "ATHLONE", "service requests": 4019 },
  { name: "CAPE TOWN CITY CENTRE", "service requests": 3999 },
  { name: "SEA POINT", "service requests": 3960 },
  { name: "BEACON VALLEY", "service requests": 3758 },
  { name: "MAITLAND", "service requests": 3711 },
  { name: "OCEAN VIEW", "service requests": 3687 },
  { name: "ROCKLANDS", "service requests": 3643 },
  { name: "DURBANVILLE", "service requests": 3623 },
  { name: "UMRHABULO TRIANGLE", "service requests": 3555 },
  { name: "KHAYELITSHA", "service requests": 3500 },
  { name: "LAVENDER HILL", "service requests": 3476 },
  { name: "OBSERVATORY", "service requests": 3471 },
  { name: "WALLACEDENE", "service requests": 3420 },
  { name: "SUNNYDALE", "service requests": 3387 },
  { name: "PARKWOOD", "service requests": 3381 },
  { name: "PORTLAND", "service requests": 3373 },
  { name: "HEIDEVELD", "service requests": 3289 },
  { name: "BROOKLYN", "service requests": 3276 },
  { name: "KENSINGTON", "service requests": 3248 },
  { name: "SCOTTSDENE", "service requests": 3209 },
  { name: "ROBINVALE", "service requests": 3204 },
  { name: "AVONDALE - WESFLEUR", "service requests": 3174 },
  { name: "MUIZENBERG", "service requests": 3127 },
  { name: "GARDENS", "service requests": 2992 },
  { name: "WESBANK", "service requests": 2988 },
  { name: "CROSSROADS", "service requests": 2944 },
  { name: "EDGEMEAD", "service requests": 2911 },
  { name: "DELFT SOUTH", "service requests": 2887 },
  { name: "KENILWORTH", "service requests": 2859 },
  { name: "PELIKAN PARK", "service requests": 2795 },
  { name: "NEWLANDS", "service requests": 2773 },
  { name: "ELSIES RIVER", "service requests": 2751 },
  { name: "BELGRAVIA", "service requests": 2745 },
  { name: "RUYTERWACHT", "service requests": 2743 },
  { name: "ASANDA", "service requests": 2730 },
  { name: "MILNERTON", "service requests": 2724 },
  { name: "LEIDEN", "service requests": 2686 },
  { name: "MELKBOSCH STRAND", "service requests": 2668 },
  { name: "WESTRIDGE - MITCHELLS PLAIN", "service requests": 2631 },
  { name: "LWANDLE", "service requests": 2622 },
  { name: "BOSTON", "service requests": 2535 },
  { name: "ILITHA PARK", "service requests": 2493 },
  { name: "UITSIG", "service requests": 2474 },
  { name: "PAROW", "service requests": 2459 },
  { name: "NOMZAMO", "service requests": 2393 },
  { name: "BERGVLIET", "service requests": 2379 },
  { name: "RYLANDS", "service requests": 2295 },
  { name: "BOTHASIG", "service requests": 2279 },
  { name: "TOWNSEND ESTATE", "service requests": 2278 },
  { name: "KUYASA", "service requests": 2239 },
  { name: "WINDERMERE", "service requests": 2223 },
  { name: "MANDELA PARK", "service requests": 2197 },
  { name: "HARARE", "service requests": 2190 },
  { name: "SEAWINDS", "service requests": 2164 },
  { name: "WOODLANDS", "service requests": 2159 },
  { name: "CAMPS BAY / BAKOVEN", "service requests": 2158 },
  { name: "ROSEDALE - KLEIN VLEI", "service requests": 2132 },
  { name: "THE HAGUE", "service requests": 2117 },
  { name: "SURREY ESTATE", "service requests": 2117 },
  { name: "PROTEA PARK - WESFLEUR", "service requests": 2065 },
  { name: "BRIDGETOWN", "service requests": 2032 },
  { name: "TOKAI", "service requests": 2029 },
  { name: "VREDEHOEK", "service requests": 2024 },
  { name: "SOUTHFIELD", "service requests": 1993 },
  { name: "PAROW VALLEY", "service requests": 1988 },
  { name: "SALT RIVER", "service requests": 1987 },
  { name: "VASCO ESTATE", "service requests": 1949 },
  { name: "DUNOON", "service requests": 1941 },
  { name: "SUMMER GREENS", "service requests": 1936 },
  { name: "ROOSENDAL", "service requests": 1932 },
  { name: "KEWTOWN", "service requests": 1923 },
  { name: "BELMONT PARK", "service requests": 1923 },
  { name: "PROTEA HEIGHTS", "service requests": 1901 },
  { name: "MALIBU VILLAGE", "service requests": 1888 },
  { name: "IKWEZI PARK", "service requests": 1879 },
  { name: "CRAWFORD", "service requests": 1866 },
  { name: "OAKDALE", "service requests": 1865 },
  { name: "GREEN POINT", "service requests": 1856 },
  { name: "SHERWOOD", "service requests": 1853 },
  { name: "KALKFONTEIN", "service requests": 1852 },
  { name: "BLOEKOMBOS", "service requests": 1846 },
  { name: "SUNNINGDALE", "service requests": 1823 },
  { name: "SIMON'S TOWN", "service requests": 1819 },
  { name: "NOORDHOEK", "service requests": 1819 },
  { name: "GLENLILY", "service requests": 1817 },
  { name: "VOORBRUG", "service requests": 1807 },
  { name: "HAZENDAL", "service requests": 1789 },
  { name: "MOWBRAY", "service requests": 1768 },
  { name: "SILVERSANDS", "service requests": 1705 },
  { name: "THORNTON", "service requests": 1686 },
  { name: "SILVERTOWN", "service requests": 1667 },
  { name: "SCOTTSVILLE", "service requests": 1660 },
  { name: "GLENCAIRN", "service requests": 1659 },
  { name: "VICTORIA MXENGE", "service requests": 1654 },
  { name: "NEW WOODLANDS", "service requests": 1646 },
  { name: "VRYGROND", "service requests": 1646 },
  { name: "DIEP RIVER", "service requests": 1618 },
  { name: "EERSTERIVIER SOUTH", "service requests": 1611 },
  { name: "JOE SLOVO PARK", "service requests": 1606 },
  { name: "VALHALLA PARK", "service requests": 1583 },
  { name: "SAREPTA", "service requests": 1566 },
  { name: "LEONSDALE", "service requests": 1538 },
  { name: "COLORADO PARK", "service requests": 1524 },
  { name: "GOODWOOD ESTATE", "service requests": 1495 },
  { name: "FOREST HEIGHTS", "service requests": 1491 },
  { name: "PANORAMA", "service requests": 1484 },
  { name: "MONTE VISTA", "service requests": 1472 },
  { name: "WELGELEGEN", "service requests": 1465 },
  { name: "ORANJEZICHT", "service requests": 1460 },
  { name: "HELDERVUE", "service requests": 1454 },
  { name: "FLORIDA", "service requests": 1442 },
  { name: "NORTHPINE", "service requests": 1440 },
  { name: "LAKESIDE", "service requests": 1437 },
  { name: "TIJGERHOF", "service requests": 1419 },
  { name: "GATESVILLE", "service requests": 1418 },
  { name: "NONQUBELA", "service requests": 1417 },
  { name: "KIRSTENHOF", "service requests": 1387 },
  { name: "CHURCHILL ESTATE", "service requests": 1382 },
  { name: "WETTON", "service requests": 1379 },
  { name: "MACASSAR", "service requests": 1378 },
  { name: "EAGLE PARK", "service requests": 1377 },
  { name: "RUGBY", "service requests": 1366 },
  { name: "BRACKENFELL SOUTH", "service requests": 1363 },
  { name: "RICHMOND ESTATE", "service requests": 1350 },
  { name: "KLEINVLEI TOWN", "service requests": 1339 },
  { name: "HEATHFIELD", "service requests": 1338 },
  { name: "WELGEMOED", "service requests": 1332 },
  { name: "ZEEKOEVLEI", "service requests": 1326 },
  { name: "KHAYA", "service requests": 1319 },
  { name: "KLIPKOP", "service requests": 1314 },
  { name: "LOEVENSTEIN", "service requests": 1314 },
  { name: "NEWFIELDS", "service requests": 1279 },
  { name: "EVERSDAL ", "service requests": 1267 },
  { name: "MACASSAR VILLAGE", "service requests": 1261 },
  { name: "MAMRE", "service requests": 1249 },
  { name: "SOMERSET WEST", "service requests": 1244 },
  { name: "KOMMETJIE", "service requests": 1239 },
  { name: "BELTHORN ESTATE", "service requests": 1226 },
  { name: "MEADOWRIDGE", "service requests": 1225 },
  { name: "RONDEBOSCH EAST", "service requests": 1202 },
  { name: "WINDSOR ESTATE", "service requests": 1198 },
  { name: "TAMBOERSKLOOF", "service requests": 1197 },
  { name: "GORDONS BAY", "service requests": 1191 },
  { name: "PAROW NORTH", "service requests": 1163 },
  { name: "FRESNAYE", "service requests": 1154 },
  { name: "FISANTEKRAAL", "service requests": 1134 },
  { name: "BELHAR EXT 23", "service requests": 1132 },
  { name: "BO-KAAP", "service requests": 1116 },
  { name: "DISTRICT SIX", "service requests": 1106 },
  { name: "ROSEBANK", "service requests": 1106 },
  { name: "DELFT 1 & 2", "service requests": 1104 },
  { name: "BEACON HILL", "service requests": 1098 },
  { name: "KALKSTEENFONTEIN", "service requests": 1090 },
  { name: "OAKGLEN", "service requests": 1086 },
  { name: "GREENVILLE GARDEN CITY", "service requests": 1077 },
  { name: "BELHAR EXT 19", "service requests": 1068 },
  { name: "WINDSOR PARK ESTATE", "service requests": 1066 },
  { name: "ENKANINI", "service requests": 1065 },
  { name: "HIGHBURY", "service requests": 1062 },
  { name: "EIKENDAL", "service requests": 1056 },
  { name: "PINEHURST", "service requests": 1041 },
  { name: "CRAVENBY", "service requests": 1036 },
  { name: "SONSTRAAL HEIGHTS", "service requests": 1035 },
  { name: "PINATI ESTATE", "service requests": 1033 },
  { name: "PHOENIX", "service requests": 1025 },
  { name: "BISHOPSCOURT", "service requests": 1024 },
  { name: "CENTURY CITY", "service requests": 1023 },
  { name: "FAIRFIELD ESTATE", "service requests": 1002 },
  { name: "FOREST VILLAGE", "service requests": 1000 },
  { name: "CAPE FARMS - DISTRICT B", "service requests": 995 },
  { name: "SANDDRIFT", "service requests": 994 },
  { name: "VREDEKLOOF", "service requests": 983 },
  { name: "DELFT 9", "service requests": 978 },
  { name: "MXOLISI PHETANI", "service requests": 973 },
  { name: "KENRIDGE", "service requests": 970 },
  { name: "WESTLAKE", "service requests": 969 },
  { name: "CONNAUGHT", "service requests": 967 },
  { name: "UITZICHT", "service requests": 954 },
  { name: "BROADLANDS PARK", "service requests": 952 },
  { name: "FOUNTAIN VILLAGE", "service requests": 952 },
  { name: "ONVERWACHT - THE STRAND", "service requests": 952 },
  { name: "BELLVILLE CBD", "service requests": 945 },
  { name: "MATROOSFONTEIN", "service requests": 932 },
  { name: "EUREKA ESTATE", "service requests": 922 },
  { name: "DENNEMERE", "service requests": 915 },
  { name: "BELHAR EXT 21", "service requests": 882 },
  { name: "BLAAUWBERGSTRAND", "service requests": 881 },
  { name: "RONDEVLEI PARK", "service requests": 858 },
  { name: "CLARKES ESTATE", "service requests": 854 },
  { name: "ELECTRIC CITY", "service requests": 854 },
  { name: "BURGUNDY", "service requests": 850 },
  { name: "STELLENBERG", "service requests": 844 },
  { name: "RIVERSIDE", "service requests": 838 },
  { name: "EYETHU", "service requests": 826 },
  { name: "PENLYN ESTATE", "service requests": 825 },
  { name: "PEERLESS PARK EAST", "service requests": 820 },
  { name: "MORGANS VILLAGE", "service requests": 811 },
  { name: "AVONDALE - PAROW", "service requests": 807 },
  { name: "HAGLEY", "service requests": 804 },
  { name: "WITSAND", "service requests": 783 },
  { name: "BRIZA", "service requests": 775 },
  { name: "LANGEBERG RIDGE", "service requests": 774 },
  { name: "HILLCREST HEIGHTS", "service requests": 772 },
  { name: "MONTAGUE GARDENS", "service requests": 766 },
  { name: "THEMBOKWEZI", "service requests": 760 },
  { name: "FAIRDALE", "service requests": 760 },
  { name: "KEMPENVILLE", "service requests": 760 },
  { name: "ELSIES RIVER INDUSTRIA", "service requests": 753 },
  { name: "BELHAR EXT 17", "service requests": 752 },
  { name: "PAARDEN EILAND", "service requests": 749 },
  { name: "EINDHOVEN", "service requests": 740 },
  { name: "AVONWOOD", "service requests": 734 },
  { name: "BONNIE BRAE", "service requests": 725 },
  { name: "SUNSET BEACH", "service requests": 724 },
  { name: "RICHWOOD", "service requests": 716 },
  { name: "MONTANA", "service requests": 711 },
  { name: "THREE ANCHOR BAY", "service requests": 708 },
  { name: "ELFINDALE", "service requests": 703 },
  { name: "HIGHBURY PARK", "service requests": 701 },
  { name: "BROADLANDS VILLAGE", "service requests": 700 },
  { name: "EPPING FOREST", "service requests": 695 },
  { name: "GOODWOOD  EXT 1", "service requests": 690 },
  { name: "NOOITGEDACHT", "service requests": 688 },
  { name: "TUSCANY GLEN", "service requests": 686 },
  { name: "TYGERDAL", "service requests": 684 },
  { name: "DE LA HAYE", "service requests": 683 },
  { name: "SERCOR PARK", "service requests": 681 },
  { name: "VIERLANDEN", "service requests": 679 },
  { name: "CAPE FARMS - DISTRICT H", "service requests": 674 },
  { name: "SCARBOROUGH", "service requests": 668 },
  { name: "WEST BEACH", "service requests": 650 },
  { name: "MORGENSTER HEIGHTS", "service requests": 650 },
  { name: "PENHILL", "service requests": 650 },
  { name: "MARTINVILLE", "service requests": 642 },
  { name: "DELFT 8", "service requests": 630 },
  { name: "BELHAR EXT 22", "service requests": 623 },
  { name: "RIVERTON ELSIES RIVER", "service requests": 622 },
  { name: "BALVENIE", "service requests": 621 },
  { name: "FLAMINGO VLEI", "service requests": 617 },
  { name: "SONEIKE II", "service requests": 615 },
  { name: "BEACONVALE", "service requests": 615 },
  { name: "BOQUINAR INDUSTRIAL AREA", "service requests": 613 },
  { name: "GORDONS BAY VILLAGE", "service requests": 612 },
  { name: "VANGUARD ESTATE", "service requests": 611 },
  { name: "STIKLAND INDUSTRIA", "service requests": 610 },
  { name: "SUN VALLEY", "service requests": 602 },
  { name: "PLATTEKLOOF GLEN", "service requests": 598 },
  { name: "BLOUBERG SANDS", "service requests": 595 },
  { name: "MITCHELLS PLAIN CBD", "service requests": 590 },
  { name: "GREENLANDS", "service requests": 589 },
  { name: "SONSTRAAL", "service requests": 589 },
  { name: "PEERLESS PARK NORTH", "service requests": 582 },
  { name: "MARCONI BEAM", "service requests": 579 },
  { name: "EPPING INDUSTRIA 2", "service requests": 579 },
  { name: "BELHAR EXT 20", "service requests": 573 },
  { name: "WESTGATE", "service requests": 569 },
  { name: "DIE WINGERD", "service requests": 568 },
  { name: "DELFT 4", "service requests": 558 },
  { name: "BELHAR EXT 18", "service requests": 553 },
  { name: "GLENHAVEN", "service requests": 553 },
  { name: "FORESHORE", "service requests": 552 },
  { name: "VREDELUST BELLVILLE", "service requests": 552 },
  { name: "ROYAL ASCOT", "service requests": 551 },
  { name: "LLANDUDNO", "service requests": 551 },
  { name: "VAN DER STEL", "service requests": 544 },
  { name: "BELHAR EXT 4", "service requests": 544 },
  { name: "PAREL VALLEI", "service requests": 540 },
  { name: "DELFT 7", "service requests": 539 },
  { name: "MORGENSTER", "service requests": 537 },
  { name: "LABIANCE", "service requests": 537 },
  { name: "SYBRAND PARK", "service requests": 536 },
  { name: "PLATTEKLOOF 3", "service requests": 535 },
  { name: "CAMELOT", "service requests": 534 },
  { name: "GROENVALLEI", "service requests": 533 },
  { name: "BLACKHEATH INDUSTRIA", "service requests": 532 },
  { name: "LAND EN ZEEZICHT", "service requests": 531 },
  { name: "BANTRY BAY", "service requests": 525 },
  { name: "SONKRING", "service requests": 523 },
  { name: "AUDAS ESTATE", "service requests": 516 },
  { name: "VICTORIA PARK", "service requests": 516 },
  { name: "BELHAR EXT 7", "service requests": 512 },
  { name: "VREDEKLOOF EAST", "service requests": 510 },
  { name: "ADRIAANSE", "service requests": 509 },
  { name: "BIG BAY", "service requests": 509 },
  { name: "WIMBLEDON ESTATE", "service requests": 507 },
  { name: "MOUNTVIEW", "service requests": 502 },
  { name: "DOOR DE KRAAL", "service requests": 502 },
  { name: "BONNIE BROOK", "service requests": 502 },
  { name: "WELCOME ESTATE", "service requests": 492 },
  { name: "MAITLAND GARDEN VILLAGE", "service requests": 491 },
  { name: "GAYLEE", "service requests": 489 },
  { name: "SUNBIRD PARK", "service requests": 486 },
  { name: "BELL GLEN", "service requests": 481 },
  { name: "DELFT 6", "service requests": 478 },
  { name: "BELHAR EXT 1", "service requests": 476 },
  { name: "WELTEVREDEN VALLEY", "service requests": 476 },
  { name: "CLIFTON", "service requests": 471 },
  { name: "CHRISMAR", "service requests": 469 },
  { name: "PAROW INDUSTRIA", "service requests": 467 },
  { name: "KALK BAY", "service requests": 466 },
  { name: "ATLANTIS INDUSTRIAL", "service requests": 463 },
  { name: "FIRLANDS", "service requests": 460 },
  { name: "FIRGROVE", "service requests": 460 },
  { name: "ENDLOVINI", "service requests": 459 },
  { name: "PLATTEKLOOF 2", "service requests": 458 },
  { name: "PROTEA VALLEY", "service requests": 456 },
  { name: "GOEDEMOED", "service requests": 454 },
  { name: "DE TIJGER", "service requests": 452 },
  { name: "THE RANGE", "service requests": 449 },
  { name: "KLEINBOSCH", "service requests": 443 },
  { name: "GORDONS STRAND ESTATE", "service requests": 443 },
  { name: "STELLENRYK", "service requests": 433 },
  { name: "JOOSTENBERGVLAKTE SMALLHOLDINGS", "service requests": 432 },
  { name: "MILNERTON RIDGE", "service requests": 432 },
  { name: "DELFT 3", "service requests": 429 },
  { name: "MORNINGSTAR", "service requests": 424 },
  { name: "DELFT 5", "service requests": 423 },
  { name: "HELENA HEIGHTS", "service requests": 421 },
  { name: "GREENFIELDS", "service requests": 420 },
  { name: "RIDGEWORTH", "service requests": 415 },
  { name: "PEERLESS PARK WEST", "service requests": 410 },
  { name: "BRACKENFELL INDUSTRIA", "service requests": 409 },
  { name: "EPPING INDUSTRIA 1", "service requests": 409 },
  { name: "AMANDA GLEN ", "service requests": 403 },
  { name: "HELDERBERG ESTATE", "service requests": 402 },
  { name: "BRACKENFELL CENTRAL", "service requests": 397 },
  { name: "MOUNTAINSIDE ESTATE", "service requests": 396 },
  { name: "AVON", "service requests": 396 },
  { name: "GOLDEN ACRE", "service requests": 395 },
  { name: "STELLENRIDGE", "service requests": 394 },
  { name: "BO OAKDALE", "service requests": 394 },
  { name: "WESTRIDGE - SOMERSET WEST", "service requests": 393 },
  { name: "ANCHORAGE PARK", "service requests": 393 },
  { name: "ELIM", "service requests": 384 },
  { name: "BURGUNDY ESTATE", "service requests": 382 },
  { name: "KAAPZICHT", "service requests": 382 },
  { name: "SIR LOWRY'S PASS", "service requests": 382 },
  { name: "OUDE WESTHOF", "service requests": 378 },
  { name: "SUN CITY", "service requests": 372 },
  { name: "HARMONY VILLAGE", "service requests": 372 },
  { name: "PAROW EAST", "service requests": 369 },
  { name: "THE CONIFERS", "service requests": 368 },
  { name: "HELDERRANT", "service requests": 366 },
  { name: "JACARANDAS", "service requests": 361 },
  { name: "FERNDALE", "service requests": 351 },
  { name: "LYNN'S VIEW", "service requests": 349 },
  { name: "MABILLE PARK", "service requests": 349 },
  { name: "CAPE FARMS - DISTRICT C", "service requests": 349 },
  { name: "GERSHAM", "service requests": 346 },
  { name: "AURORA", "service requests": 345 },
  { name: "MOUILLE POINT", "service requests": 340 },
  { name: "ST DUMAS", "service requests": 340 },
  { name: "BELHAR EXT 12", "service requests": 339 },
  { name: "BARONETCY ESTATE", "service requests": 339 },
  { name: "SONEIKE I", "service requests": 339 },
  { name: "LANGEBERG HOOGTE", "service requests": 338 },
  { name: "BELHAR EXT 13", "service requests": 338 },
  { name: "ZOO PARK", "service requests": 336 },
  { name: "SONNEKUIL", "service requests": 336 },
  { name: "OOSTERZEE-BELLVILLE", "service requests": 335 },
  { name: "SABATA DALINDYEBO SQUARE", "service requests": 334 },
  { name: "BRANTWOOD", "service requests": 333 },
  { name: "SOUTHFORK", "service requests": 332 },
  { name: "VAN RIEBEECKSHOF", "service requests": 331 },
  { name: "D'URBANVALE", "service requests": 327 },
  { name: "PELLA", "service requests": 327 },
  { name: "ST JAMES", "service requests": 326 },
  { name: "PROTEA VILLAGE", "service requests": 325 },
  { name: "WELLWAY PARK EAST", "service requests": 322 },
  { name: "CLOVELLY", "service requests": 322 },
  { name: "DURBANVILLE HILLS", "service requests": 319 },
  { name: "BLUE DOWNS CBD", "service requests": 319 },
  { name: "NEW MACASSAR", "service requests": 318 },
  { name: "DE BRON", "service requests": 318 },
  { name: "BELHAR EXT 10", "service requests": 318 },
  { name: "SILVEROAKS", "service requests": 315 },
  { name: "DE KUILEN", "service requests": 314 },
  { name: "BELHAR EXT 11", "service requests": 313 },
  { name: "WELGEDACHT", "service requests": 311 },
  { name: "KLEINBRON", "service requests": 310 },
  { name: "HAPPY VALLEY", "service requests": 309 },
  { name: "SAXON INDUSTRIAL", "service requests": 308 },
  { name: "STELLENDALE", "service requests": 306 },
  { name: "NEW SCHEME", "service requests": 305 },
  { name: "EKUPHUMLENI", "service requests": 304 },
  { name: "HOHEIZEN", "service requests": 303 },
  { name: "ELNOR", "service requests": 302 },
  { name: "BELHAR EXT 16", "service requests": 300 },
  { name: "DOBSON", "service requests": 300 },
  { name: "ONVERWACHT - GORDON'S BAY", "service requests": 298 },
  { name: "AMANDELRUG", "service requests": 296 },
  { name: "BUH-REIN ESTATE", "service requests": 295 },
  { name: "CLAMHALL", "service requests": 294 },
  { name: "PEACOCK CLOSE", "service requests": 290 },
  { name: "CHARLESVILLE", "service requests": 290 },
  { name: "OAKDENE", "service requests": 287 },
  { name: "LA ROCHELLE", "service requests": 286 },
  { name: "GLENWOOD", "service requests": 285 },
  { name: "THE CREST", "service requests": 284 },
  { name: "KELDERHOF", "service requests": 283 },
  { name: "BELGRAVIA -BELLVILLE", "service requests": 281 },
  { name: "MISSION GROUNDS", "service requests": 280 },
  { name: "MIKPUNT", "service requests": 279 },
  { name: "RUSTDAL", "service requests": 278 },
  { name: "PELIKAN HEIGHTS", "service requests": 274 },
  { name: "PLATTEKLOOF 1", "service requests": 273 },
  { name: "HERITAGE PARK", "service requests": 271 },
  { name: "DEACONVILLE", "service requests": 271 },
  { name: "BRACKEN HEIGHTS", "service requests": 269 },
  { name: "BIZWENI", "service requests": 267 },
  { name: "EIKENBOSCH KUILS RIVER", "service requests": 265 },
  { name: "KILLARNEY GARDENS", "service requests": 263 },
  { name: "BELLAIR", "service requests": 262 },
  { name: "AUSTINVILLE", "service requests": 262 },
  { name: "BLOEMHOF", "service requests": 260 },
  { name: "HIGHLANDS VILLAGE", "service requests": 259 },
  { name: "BELHAR EXT 6", "service requests": 257 },
  { name: "SOMERSET RIDGE", "service requests": 255 },
  { name: "KRAAIFONTEIN", "service requests": 255 },
  { name: "SANDOWN", "service requests": 254 },
  { name: "BELRAIL", "service requests": 252 },
  { name: "DE DUIN", "service requests": 251 },
  { name: "ADMIRALS PARK", "service requests": 250 },
  { name: "DRIFTSANDS", "service requests": 250 },
  { name: "ROUXVILLE", "service requests": 248 },
  { name: "HUNTERS CREEK", "service requests": 246 },
  { name: "KUILSRIVIER SOUTH SMALLHOLDINGS", "service requests": 245 },
  { name: "BETHANIE", "service requests": 240 },
  { name: "MOUNTAINSIDE", "service requests": 239 },
  { name: "STELLENBOSCH FARMS", "service requests": 238 },
  { name: "FAIRVIEW GOLF ESTATE", "service requests": 238 },
  { name: "BELHAR EXT 3", "service requests": 238 },
  { name: "GORDONS BAY EXT 12", "service requests": 237 },
  { name: "GRAANENDAL", "service requests": 237 },
  { name: "SUNRIDGE", "service requests": 236 },
  { name: "BELHAR EXT 2", "service requests": 236 },
  { name: "EVERSDAL HEIGHTS", "service requests": 235 },
  { name: "DE OUDE SPRUIT", "service requests": 235 },
  { name: "LA SANDRA", "service requests": 232 },
  { name: "KLEINBEGIN", "service requests": 232 },
  { name: "WINSLOW", "service requests": 232 },
  { name: "ST MICHAELS", "service requests": 232 },
  { name: "BLOUBERG RISE", "service requests": 232 },
  { name: "TWIN PALMS", "service requests": 232 },
  { name: "VREDENBERG - BELLVILLE", "service requests": 230 },
  { name: "BELHAR EXT 14", "service requests": 229 },
  { name: "TEMPERANCE TOWN", "service requests": 224 },
  { name: "PAARDE VLEI", "service requests": 221 },
  { name: "STRAND INDUSTRIA", "service requests": 220 },
  { name: "SONNENDAL", "service requests": 217 },
  { name: "BRENTWOOD PARK - BLUE DOWNS", "service requests": 216 },
  { name: "BELLVILLE SOUTH INDUSTRIA", "service requests": 216 },
  { name: "JAGTERSHOF", "service requests": 215 },
  { name: "ROME GLEN", "service requests": 215 },
  { name: "VIKING VILLAGE", "service requests": 212 },
  { name: "EDENPARK", "service requests": 212 },
  { name: "VERGESIG", "service requests": 211 },
  { name: "AMANDELSIG", "service requests": 211 },
  { name: "LA CONCORDE", "service requests": 208 },
  { name: "WEST RIDING", "service requests": 206 },
  { name: "THE LINK", "service requests": 204 },
  { name: "VYGEBOOM", "service requests": 203 },
  { name: "HELDERBERG VILLAGE", "service requests": 202 },
  { name: "KINGSTON", "service requests": 202 },
  { name: "CHANTECLER", "service requests": 201 },
  { name: "STUART'S HILL", "service requests": 201 },
  { name: "KUILS RIVER COMMON", "service requests": 200 },
  { name: "VOELVLEI", "service requests": 199 },
  { name: "DES HAMPDEN", "service requests": 194 },
  { name: "VALMARY PARK", "service requests": 193 },
  { name: "GOODRAIL", "service requests": 190 },
  { name: "HYDE PARK", "service requests": 184 },
  { name: "DENNEGEUR", "service requests": 181 },
  { name: "DURMONTE", "service requests": 181 },
  { name: "TRIANGLE FARM", "service requests": 181 },
  { name: "OKAVANGO PARK", "service requests": 179 },
  { name: "RICHMOND", "service requests": 179 },
  { name: "NORMANDIE ESTATE", "service requests": 178 },
  { name: "GARDEN VILLAGE", "service requests": 177 },
  { name: "PARELVALLEI KLEINHOEWES", "service requests": 177 },
  { name: "EVERITE INDUSTRIA", "service requests": 176 },
  { name: "GREENWAYS", "service requests": 176 },
  { name: "BELHAR EXT 8", "service requests": 176 },
  { name: "ERINVALE ESTATE", "service requests": 174 },
  { name: "AIRPORT CITY", "service requests": 173 },
  { name: "GEORGE PARK", "service requests": 169 },
  { name: "ROUNDHAY", "service requests": 169 },
  { name: "GOLDEN HILL EXT 1", "service requests": 169 },
  { name: "BLOMTUIN", "service requests": 168 },
  { name: "VREDEKLOOF HEIGHTS", "service requests": 167 },
  { name: "RUWARI", "service requests": 165 },
  { name: "GANTS PARK", "service requests": 165 },
  { name: "BRANDWAG", "service requests": 162 },
  { name: "BLOMMENDAL", "service requests": 161 },
  { name: "HELDERBERG PARK", "service requests": 160 },
  { name: "SPANISH FARM", "service requests": 159 },
  { name: "KLIPDAM", "service requests": 158 },
  { name: "BLOUBERGRANT", "service requests": 158 },
  { name: "ARAUNA", "service requests": 158 },
  { name: "PHILIPPI PARK", "service requests": 157 },
  { name: "BOSBELL", "service requests": 156 },
  { name: "BELHAR EXT 9", "service requests": 153 },
  { name: "SCHOONGEZICHT", "service requests": 153 },
  { name: "ROSENDAL", "service requests": 153 },
  { name: "BELHAR EXT 5", "service requests": 152 },
  { name: "TURTLE CREEK", "service requests": 151 },
  { name: "EVERGLEN", "service requests": 150 },
  { name: "SPRINGBOKPARK", "service requests": 150 },
  { name: "VREDELUST KUILS RIVER", "service requests": 149 },
  { name: "HARDEKRAALTJIE", "service requests": 148 },
  { name: "TYGERVALLEY WATERFRONT", "service requests": 147 },
  { name: "SAXENBURG PARK 1", "service requests": 147 },
  { name: "STRANDVALE", "service requests": 146 },
  { name: "HELDERBERG INDUSTRIAL PARK", "service requests": 146 },
  { name: "PHILADELPHIA", "service requests": 144 },
  { name: "GRACELAND", "service requests": 143 },
  { name: "KRAAIFONTEIN INDUSTRIA", "service requests": 143 },
  { name: "SAND INDUSTRIA", "service requests": 143 },
  { name: "GOLIATH ESTATE", "service requests": 142 },
  { name: "GOEDEHOOP", "service requests": 139 },
  { name: "DANARAND", "service requests": 139 },
  { name: "BOSONIA", "service requests": 138 },
  { name: "TYGERVALLEY", "service requests": 138 },
  { name: "CHRIS HANI PARK", "service requests": 137 },
  { name: "ZEVENDAL", "service requests": 137 },
  { name: "MARINDA PARK", "service requests": 137 },
  { name: "GORDON HEIGHTS", "service requests": 136 },
  { name: "HINDLE PARK", "service requests": 135 },
  { name: "CAREY PARK", "service requests": 134 },
  { name: "HIGH RIDING", "service requests": 132 },
  { name: "SHIRLEY PARK", "service requests": 129 },
  { name: "MOUNTAINSIDE EXT 2", "service requests": 128 },
  { name: "CHRIS NISSEN PARK", "service requests": 126 },
  { name: "PEARL RISE", "service requests": 126 },
  { name: "HAASENDAL", "service requests": 126 },
  { name: "KAAPSIG", "service requests": 125 },
  { name: "LOURENSIA PARK", "service requests": 125 },
  { name: "HARBOUR ISLAND", "service requests": 125 },
  { name: "N1-STAD", "service requests": 124 },
  { name: "MONTEVIDEO", "service requests": 122 },
  { name: "RIVERGATE", "service requests": 121 },
  { name: "CLARA ANNA FONTEIN", "service requests": 121 },
  { name: "SANDVLEI", "service requests": 120 },
  { name: "HELDERZICHT", "service requests": 120 },
  { name: "MIKRO PARK", "service requests": 118 },
  { name: "DORHILL", "service requests": 117 },
  { name: "BRIDGEWATER", "service requests": 115 },
  { name: "JOUBERTPARK", "service requests": 115 },
  { name: "DURBANVILLE MEADOWS", "service requests": 113 },
  { name: "SACK'S CIRCLE INDUSTRIA", "service requests": 112 },
  { name: "JACQUES HILL", "service requests": 110 },
  { name: "FISANTEKRAAL INDUSTRIAL", "service requests": 109 },
  { name: "STELLENBOSCH FARMS (KUILSRIVIER)", "service requests": 109 },
  { name: "DURBELL", "service requests": 109 },
  { name: "BRIDGEBANK", "service requests": 108 },
  { name: "BROADLANDS", "service requests": 107 },
  { name: "KUILSRIVIER INDUSTRIA", "service requests": 106 },
  { name: "MONTANA EXTENSION", "service requests": 105 },
  { name: "SELBORNE", "service requests": 104 },
  { name: "WESTERDALE", "service requests": 103 },
  { name: "CROYDON", "service requests": 101 },
  { name: "ZEVENZICHT", "service requests": 100 },
  { name: "WP PARK", "service requests": 100 },
  { name: "PEARL MARINA", "service requests": 99 },
  { name: "SITARI COUNTRY ESTATE", "service requests": 98 },
  { name: "HUMANSHOF", "service requests": 98 },
  { name: "WILDWOOD", "service requests": 98 },
  { name: "MALL TRIANGLE", "service requests": 97 },
  { name: "AVALON ESTATE", "service requests": 96 },
  { name: "NORTHGATE", "service requests": 96 },
  { name: "LAGOON BEACH", "service requests": 95 },
  { name: "WINGFIELD", "service requests": 95 },
  { name: "HIGHGATE", "service requests": 95 },
  { name: "SANLAMHOF", "service requests": 95 },
  { name: "RUITERSHOOGTE", "service requests": 94 },
  { name: "MANSFIELD INDUSTRIA", "service requests": 94 },
  { name: "WELLWAY PARK", "service requests": 94 },
  { name: "TABLE MOUNTAIN", "service requests": 94 },
  { name: "LONGDOWN ESTATE", "service requests": 92 },
  { name: "MORNINGSIDE", "service requests": 91 },
  { name: "NERINA", "service requests": 91 },
  { name: "MORGAN INDUSTRIA", "service requests": 91 },
  { name: "MONTE SERENO", "service requests": 89 },
  { name: "ANNANDALE", "service requests": 89 },
  { name: "LOUMAR", "service requests": 88 },
  { name: "OLIVE GROVE", "service requests": 87 },
  { name: "SILVERTOWN - KHAYELITSHA", "service requests": 86 },
  { name: "MONTAGUE", "service requests": 86 },
  { name: "HOOGSTEDE", "service requests": 86 },
  { name: "HATTON", "service requests": 85 },
  { name: "FIRGROVE RURAL", "service requests": 84 },
  { name: "BENE TOWNSHIP", "service requests": 84 },
  { name: "STEENBRAS VIEW", "service requests": 83 },
  { name: "MEYERHOF", "service requests": 82 },
  { name: "SUMMERVILLE", "service requests": 80 },
  { name: "WELGEVONDEN", "service requests": 80 },
  { name: "ONVERWACHT VILLAGE", "service requests": 79 },
  { name: "MALMESBURY FARMS", "service requests": 78 },
  { name: "SIRROCCO'S", "service requests": 78 },
  { name: "MALL INTERCHANGE", "service requests": 77 },
  { name: "HEARTLAND HISTORIC PRECINCT", "service requests": 76 },
  { name: "KLIPHEUWEL HOUSING SCHEME", "service requests": 76 },
  { name: "TRANSNET MARSHALLING YARD", "service requests": 75 },
  { name: "DE WIJNLANDEN ESTATE", "service requests": 74 },
  { name: "BOTTELARY SMALLHOLDINGS 2", "service requests": 74 },
  { name: "PAROW GOLF COURSE", "service requests": 74 },
  { name: "AAN DE WIJNLANDEN ESTATE", "service requests": 73 },
  { name: "KANONBERG", "service requests": 73 },
  { name: "LANGEBERG VILLAGE", "service requests": 72 },
  { name: "BEL'AIRE", "service requests": 71 },
  { name: "MISTY CLIFFS", "service requests": 71 },
  { name: "CAPE TOWN AIRPORT", "service requests": 70 },
  { name: "DELRO VILLAGE", "service requests": 70 },
  { name: "SOMERSET WEST BUSINESS PARK", "service requests": 69 },
  { name: "FRAAIGELEGEN", "service requests": 68 },
  { name: "MARVINPARK", "service requests": 68 },
  { name: "ROSENPARK", "service requests": 68 },
  { name: "BOTFONTEIN SMALLHOLDINGS", "service requests": 68 },
  { name: "YSTERPLAAT", "service requests": 68 },
  { name: "BLOMVLEI", "service requests": 67 },
  { name: "FERNWOOD", "service requests": 66 },
  { name: "SEA BREEZE PARK", "service requests": 66 },
  { name: "PROTEAVILLE", "service requests": 66 },
  { name: "STIKLAND", "service requests": 66 },
  { name: "BELHAR EXT 15", "service requests": 65 },
  { name: "ILLAIRE", "service requests": 64 },
  { name: "WEMBLEY PARK", "service requests": 62 },
  { name: "MACASSAR BEACH", "service requests": 60 },
  { name: "BRANDWACHT", "service requests": 59 },
  { name: "O'KENNEDYVILLE", "service requests": 59 },
  { name: "LOUCHARMANTE", "service requests": 58 },
  { name: "PAARL FARMS", "service requests": 58 },
  { name: "ACACIA PARK", "service requests": 57 },
  { name: "BENNO PARK", "service requests": 57 },
  { name: "MODDERDAM", "service requests": 57 },
  { name: "CAPE GATE", "service requests": 56 },
  { name: "HIGHVELD", "service requests": 56 },
  { name: "RACING PARK", "service requests": 55 },
  { name: "WORLD'S VIEW - SOMERSET WEST", "service requests": 55 },
  { name: "SILVERTAS", "service requests": 52 },
  { name: "HEEMSTEDE", "service requests": 52 },
  { name: "ANNANDALE FARM", "service requests": 52 },
  { name: "SCHONENBERG", "service requests": 52 },
  { name: "ZEVENWACHT COUNTRY ESTATE", "service requests": 51 },
  { name: "EERSTERIVIER INDUSTRIA", "service requests": 51 },
  { name: "FALSE BAY COASTAL PARK", "service requests": 50 },
  { name: "METRO", "service requests": 48 },
  { name: "JONKERS HOOGTE", "service requests": 47 },
  { name: "CARWICK", "service requests": 45 },
  { name: "ROSEDALE - DURBANVILLE", "service requests": 43 },
  { name: "BRENTWOOD PARK - DURBANVILLE", "service requests": 43 },
  { name: "BELVEDERE TYGERBERG", "service requests": 40 },
  { name: "KLOOFZICHT", "service requests": 39 },
  { name: "DE GRENDEL FARM", "service requests": 37 },
  { name: "NUTWOOD", "service requests": 37 },
  { name: "DE VELDE", "service requests": 37 },
  { name: "PROTEA PARK - GORDON'S BAY", "service requests": 36 },
  { name: "SMARTIE TOWN", "service requests": 35 },
  { name: "WEDDERWILL ESTATE", "service requests": 35 },
  { name: "KALAMUNDA", "service requests": 35 },
  { name: "MONWABISI", "service requests": 34 },
  { name: "BRACKENFELL COMMON", "service requests": 34 },
  { name: "MONTCHERE", "service requests": 34 },
  { name: "WAIROA", "service requests": 33 },
  { name: "CROYDON OLIVE ESTATE", "service requests": 33 },
  { name: "BARNET MOLOKWANA CORNER", "service requests": 33 },
  { name: "NATURE'S VALLEY", "service requests": 31 },
  { name: "ATLAS GARDENS BUSINESS PARK", "service requests": 31 },
  { name: "GOEDE HOOP", "service requests": 30 },
  { name: "THE STABLES", "service requests": 30 },
  { name: "LA MONTAGNE", "service requests": 29 },
  { name: "DOOR DE KRAAL FARM", "service requests": 29 },
  { name: "SIGNAL HILL / LIONS HEAD", "service requests": 29 },
  { name: "AIRPORT", "service requests": 28 },
  { name: "UWC", "service requests": 28 },
  { name: "EENSGEVONDEN", "service requests": 27 },
  { name: "SIR LOWRY'S PASS VILLAGE CENTRE", "service requests": 27 },
  { name: "OUDEKRAAL", "service requests": 27 },
  { name: "ANTILLES/CAYMAN BEACH", "service requests": 26 },
  { name: "SAXENBURG PARK 2", "service requests": 26 },
  { name: "ZEVENWACHT FARM VILLAGE", "service requests": 25 },
  { name: "BRAEVIEW", "service requests": 24 },
  { name: "FAURE", "service requests": 23 },
  { name: "BOSKLOOF", "service requests": 23 },
  { name: "WYNLAND INDUSTRIAL PARK", "service requests": 23 },
  { name: "STELLENBOSCH FARMS (BLUE DOWNS)", "service requests": 22 },
  { name: "VOGELVLEI", "service requests": 22 },
  { name: "NATURES VALLEY", "service requests": 21 },
  { name: "CROYDON VINEYARD ESTATE", "service requests": 20 },
  { name: "LETRU", "service requests": 20 },
  { name: "VREDENBERG - SOMERSET WEST", "service requests": 19 },
  { name: "SOMERSET FOREST", "service requests": 19 },
  { name: "VREDENZICHT", "service requests": 18 },
  { name: "BERBAGO", "service requests": 18 },
  { name: "CPUT", "service requests": 18 },
  { name: "WYNBERG NU", "service requests": 18 },
  { name: "ASLA PARK", "service requests": 17 },
  { name: "WP SHOWGROUNDS", "service requests": 16 },
  { name: "WELMOED CEMETERY", "service requests": 16 },
  { name: "DUNROBIN", "service requests": 16 },
  { name: "SILWERBOOMKLOOF", "service requests": 15 },
  { name: "SOMERSET WEST NATURE RESERVE", "service requests": 15 },
  { name: "SOMERSET WEST COUNTRY CLUB", "service requests": 15 },
  { name: "SAXONWOOD", "service requests": 14 },
  { name: "NIEUW MAASTRECHT-1", "service requests": 14 },
  { name: "TYGERBERG HOSPITAL", "service requests": 13 },
  { name: "STELLENBOSCH UNIV", "service requests": 13 },
  { name: "CASTLE ROCK", "service requests": 12 },
  { name: "TRE DONNE", "service requests": 12 },
  { name: "BELLVILLE TEACHERS COLLEGE", "service requests": 11 },
  { name: "HEARTLAND BEACH ROAD PRECINCT", "service requests": 11 },
  { name: "ZEVENWACHT RETIREMENT VILLAGE", "service requests": 11 },
  { name: "WORLD'S VIEW - CALEDON FARMS", "service requests": 11 },
  { name: "STIKLAND HOSPITAAL", "service requests": 11 },
  { name: "KRAAIFONTEIN EAST", "service requests": 9 },
  { name: "MALL MOTOR CITY", "service requests": 9 },
  { name: "DEEPFREEZE", "service requests": 9 },
  { name: "KING DAVID COUNTRY CLUB", "service requests": 9 },
  { name: "RICHMOND PARK", "service requests": 9 },
  { name: "GOOD HOPE", "service requests": 8 },
  { name: "KUILS RIVER SPORTS GROUNDS", "service requests": 7 },
  { name: "WESFLEUR", "service requests": 7 },
  { name: "LILLYDALE", "service requests": 7 },
  { name: "KLEIN ZEVENWACHT", "service requests": 7 },
  { name: "BELLVILLE LANDFILL", "service requests": 6 },
  { name: "PETROSA TANK FARM", "service requests": 6 },
  { name: "HELDERBERG RURAL", "service requests": 6 },
  { name: "BONGANI", "service requests": 5 },
  { name: "ZEVENWACHT MALL", "service requests": 5 },
  { name: "BOTTELARY SMALLHOLDINGS 1", "service requests": 3 },
  { name: "ROBBEN ISLAND", "service requests": 3 },
  { name: "ROTTERDAM", "service requests": 3 },
  { name: "SPRINGFIELD", "service requests": 3 },
  { name: "WOLFGAT NATURE RESERVE", "service requests": 3 },
  { name: "STRAND GOLF CLUB", "service requests": 3 },
  { name: "DREAMWORLD", "service requests": 2 },
  { name: "JAN KRIEL", "service requests": 2 },
  { name: "SMITSWINKELBAAI", "service requests": 1 },
  { name: "WELMOED ESTATE", "service requests": 1 },
  { name: "NIEUW MAASTRECHT-2", "service requests": 1 },
];
